#!/usr/bin/env bash
# Bash script sets up new linux/UNIX environments
# USAGE: ./path_to_file/sandbox_initializer {token} {github username} {github email}

# Run update/upgrade
sudo apt update -y
sudo apt upgrade -y

cd ~

# Clone all git repos
git clone https://$1@github.com/$2/holbertonschool-AirBnB_clone_v4.git
cd holbertonschool-AirBnB_clone_v4
git remote set-url origin https://$2:$1@github.com/$2/holbertonschool-AirBnB_clone_v4.git
# git clone https://$1@github.com/$2/Pointers_Live_Coding.git
# git clone https://$1@github.com/$2/holbertonschool-higher_level_programming.git
# git clone https://$1@github.com/$2/Misc.git
# git clone https://$1@github.com/$2/holbertonschool-AirBnB_clone.git
# git clone https://$1@github.com/$2/holbertonschool-system_engineering-devops.git
# git clone https://$1@github.com/$2/holberton-system_engineering-devops.git
# git clone https://$1@github.com/$2/holbertonschool-monty.git
# git clone https://$1@github.com/$2/holbertonschool-low_level_programming.git
# git clone https://$1@github.com/$2/holbertonschool-simple_shell.git
# git clone https://$1@github.com/$2/shell_prep.git
# git clone https://$1@github.com/$2/holbertonschool-printf.git
# git clone https://$1@github.com/$2/holbertonschool-zero_day.git
# git clone https://$1@github.com/$2/zero_day.git
# git clone https://$1@github.com/$2/your_first_code.git

# Set git values
git config --global user.email "$3"
git config --global user.name "$2"

# Update bashrc
mv ~/.bashrc ~/.bashrc_backup
cp ~/hbtn-sandbox_initializer/.bashrc ~

# Install flask
pip3 install flask

exec bash
